In [36]:
import numpy as np 

array=np.array([
    [0,1,2,3], 
    [4,5,6,7], 
    [8,9,10,11], 
]) 
print("MATRIZ DEFAULT")
print(array)

MATRIZ DEFAULT
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
print("Muestre como extraer el elemento '5'")
print(array[1, 1])
print("")

Muestre como extraer el elemento '5'
5



In [42]:
print("Extraiga o muestre la segunda fila de la matriz. row=array[1,:]")
print(array[1, :])

Extraiga o muestre la segunda fila de la matriz. row=array[1,:]
[4 5 6 7]


In [41]:
print("Extraiga o muestre la tercera columna de la matriz.")
print(array[:, 2])

Extraiga o muestre la tercera columna de la matriz.
[ 2  6 10]


In [40]:
print("Muestre la submatriz las 2 columnas centrales.")
print(array[0:3,1:3])

Muestre la submatriz las 2 columnas centrales.
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [39]:
print("Muestre todos los datos mayores que “3”.")
print(array[array > 3])

Muestre todos los datos mayores que “3”.
[ 4  5  6  7  8  9 10 11]


In [38]:
print("Muestre todos los datos pares.")
print(array[array %2 == 0])

Muestre todos los datos pares.
[ 0  2  4  6  8 10]
