In [1]:
# Ejercicio.- Analice el archivo adjunto y su código. Realice un menú donde se muestre lo siguiente.
# 1)Crear vector (arreglo unidimensional) se preguntará cantidad de elementos. 
# 2)Crear matriz (arreglo multidimensional) se preguntará cantidad de renglones y elementos correspondientes.
# 3) Operaciones: Se escogerá la operación que se desea (Suma, Resta, Multiplicación, División entera). 
# 4) Operaciones Especiales (Operaciones con numero Pi, funciones trigonométricas y Logaritmo natural).
# 5)Crear Matriz rectangular y cuadrada de ceros. 
# 6)Crear Matriz rectangular y cuadrada de unos.
# 7) Crear Matriz Identidad.

import numpy as np
a1=np.array([1,2,3]) #Arreglo unidimensional
print("a=",a1) 
print(type(a1)) #Mostramos tipo del objeto
print("")

a2=np.array([[1,2],[3,4]]) #Arreglo bidimensional formato ([[renglón1],[renglón2]]) 
print(a2)
print("")
 
#Operaciones Básicas
a1s=a1+7 #suma+7  
print("a1s =",a1s)
print("")
a1m=a1*3 #multiplica x 3
print("a1m =",a1m)
print("")
a1sen=np.sin(a1) #valores de Seno en Radianes
print("a1sen =",a1sen)

print("")
a2=np.array([[0,np.pi],[np.pi/2,np.pi/3]])
print("")
print("a2 = ",a2 )
print("")
a3=np.sin(a2) #valores de Seno en Radianes
print("a3 =",a3)

print("") 

#Otra forma de escribir matrices

am=np.array([
	[0,1,2,3],
	[4,5,6,7],
	[8,9,10,11],
	])
print(am)
#array 

#array 


a= [1 2 3]
<class 'numpy.ndarray'>

[[1 2]
 [3 4]]

a1s = [ 8  9 10]

a1m = [3 6 9]

a1sen = [0.84147098 0.90929743 0.14112001]


a2 =  [[0.         3.14159265]
 [1.57079633 1.04719755]]

a3 = [[0.00000000e+00 1.22464680e-16]
 [1.00000000e+00 8.66025404e-01]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
