In [41]:
import numpy as np 
import math as mt
tamaño = 3
cubicTamaño = tamaño**2
array_nd = np.arange(cubicTamaño) 
print(array_nd) 

[0 1 2 3 4 5 6 7 8]


In [ ]:
# 1) Transforme este arreglo de una dimensión en dos dimensiones (Matriz). 

In [34]:
array_nd = np.resize(array_nd,(tamaño,tamaño))
print(array_nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
# 2) Regrese el arreglo a su forma original. 

In [35]:
array_nd = np.reshape(array_nd, array_2d.size)
print(Narray_1d)

[0 1 2 3 4 5 6 7 8]


In [10]:
# 3) Crear 2 arreglos de 2 dimensiones con datos enteros 

In [53]:
tope = 2 * cubicTamaño
X = np.arange(cubicTamaño).reshape(tamaño,tamaño)
print(X)
Y = np.arange(cubicTamaño,tope, 1).reshape(tamaño,tamaño)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
# concatenarlos de manera vertical y horizontal con los comandos vstack y hstack. 

In [54]:
print("Concatenacion vertical")
print(np.vstack((X,Y)))
print("Concatenacion horizontal")
print(np.hstack((X,Y)))

Concatenacion vertical
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Concatenacion horizontal
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]
