In [7]:
# 1) La función de np.random: Colocar 2 ejemplos en código. 
import numpy as np
rng = np.random.default_rng()

# Cara o cruz
while True:
    X = input("Tirar una moeda al azar? [S/N]: ")
    if X.lower() != "s":
        break
    if rng.random()>0.5:
        print("Cara")
    else:
        print("Cruz")
    input("Presione enter para continuar")

Tirar una moeda al azar? [S/N]:  n


In [9]:
# Arreglo lleno con numeros random
print("Creacion de una matriz nxn de numeros random")
while True:
    X = input("Igresa la cantidad de columnas")
    if X.isdigit():
        break
    else:
        print("Ingresa un valor entero")
while True:
    Y = input("Igresa la cantidad de renglones")
    if Y.isdigit():
        break
    else:
        print("Ingresa un valor entero")
X = int(X)
Y = int(Y)
print("Matriz de enteros [1-100]")
print(np.random.randint(0, 100, (Y, X)) )
print("Matriz de decimales [0-1]")
print(np.random.rand(Y, X) )

Creacion de una matriz nxn de numeros random


Igresa la cantidad de columnas 10
Igresa la cantidad de renglones 10


Matriz de enteros [1-100]
[[ 9 54 69 50 87 63 63 16 33 18]
 [94 71 11 42 50 17  5 18 94 86]
 [68  0 13 61 53 58 74 89 91 18]
 [43 21 38 70 60 19 25 52 18 51]
 [77 96 83 96 27 52 11 73 36 37]
 [86 25 78 86 29 78 11 63 77 40]
 [78 75 64 83 97 12 13 17 62 34]
 [36 26 17 88  4 63 64 57 91  8]
 [26 82 64 80 60 60 82 70 96 70]
 [50 68 20 55 91  0 22  6 26 89]]
Matriz de decimales [0-1]
[[0.36771718 0.76909558 0.41657675 0.79421711 0.22938001 0.97055481
  0.52574152 0.45384454 0.65555287 0.54202372]
 [0.86138638 0.82145269 0.74029105 0.8120821  0.76219286 0.41922275
  0.93777413 0.54639746 0.96558694 0.933525  ]
 [0.12530402 0.83870859 0.90557672 0.21853103 0.32834441 0.95344953
  0.99200677 0.16249531 0.83617761 0.46789844]
 [0.38225929 0.46294418 0.63556236 0.88104302 0.1800462  0.9946545
  0.60334991 0.34126162 0.42810707 0.07071005]
 [0.31633351 0.0538414  0.4022291  0.90265861 0.20877157 0.47613167
  0.80616334 0.51631179 0.58513849 0.89990302]
 [0.82845665 0.65107551 0.17207526 0.313089

In [15]:
# 2) La función de np.linspace: Colocar 2 ejemplos en código.
a = np.linspace(0, 1, num=9)
print(a)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [13]:
#retstep=True que tambien retorne de cuando es el avanze entre cada numero
#num=5 especifica que se generen 5 valores separados de forma equivalente
array, c = np.linspace(0, 100, num=5, retstep=True)
print("Paso:", c)
print("Arreglo:", array)

Paso: 25.0
Arreglo: [  0.  25.  50.  75. 100.]


In [36]:
# 3) Operaciones Matemáticas Básicas: Se escogerán las que no se han utilizado (Exponenciación, Raíz cuadrada, Logaritmos en varias bases).
# endpoint=False excliye e primer valor del resultado.
arreglobase = (np.linspace(0, 10, num=10, endpoint=False).reshape(2, 5))+1
print("Arreglo inicial")
print(arreglobase)

Arreglo inicial
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [37]:
# Raices de todo el arreglo
print(np.sqrt(arreglobase))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


In [40]:
# Exponenciacion
print("Cuadrado")
print(np.power(arreglobase,2))

print("Cubo")
print(np.power(arreglobase,3))

print("Exponenciacion de euler")
print(np.exp(arreglobase))

Cuadrado
[[  1.   4.   9.  16.  25.]
 [ 36.  49.  64.  81. 100.]]
Cubo
[[   1.    8.   27.   64.  125.]
 [ 216.  343.  512.  729. 1000.]]
Exponenciacion de euler
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]


In [43]:
# Logaritmo
print("Logaritmo en base 2")
print(np.log(arreglobase) / np.log(2))

print("Logaritmo en base 3")
print(np.log(arreglobase) / np.log(3))

print("Logaritmo en base 8")
print(np.log(arreglobase) / np.log(8))

Logaritmo en base 2
[[0.         1.         1.5849625  2.         2.32192809]
 [2.5849625  2.80735492 3.         3.169925   3.32192809]]
Logaritmo en base 3
[[0.         0.63092975 1.         1.26185951 1.46497352]
 [1.63092975 1.77124375 1.89278926 2.         2.09590327]]
Logaritmo en base 8
[[0.         0.33333333 0.52832083 0.66666667 0.77397603]
 [0.86165417 0.93578497 1.         1.05664167 1.10730936]]
